### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by sduff**
Changed "Terraform policies" to "Sentinel policies"

### CODE REVIEW

**Review by hcrhall — COMMENTED** [review]
@sduff thanks for raising this PR. Are you able to provide a bit more context behind this change and why you feel it is necessary?

**Comment by sduff** [comment]
Hi @hcrhall.
Perhaps I am being pedantic, but it seems the wording is incorrect. There is no such thing as a Terraform Policy, these are Sentinel Policies in this repo. 
The same applies for other Hashicorp sentinel repos (hashicorp/policy-library-gcp-compute-terraform, hashicorp/policy-library-azure-storage-terraform).

**Comment by hcrhall** [comment]
> Hi @hcrhall. Perhaps I am being pedantic, but it seems the wording is incorrect. There is no such thing as a Terraform Policy, these are Sentinel Policies in this repo. The same applies for other Hashicorp sentinel repos (hashicorp/policy-library-gcp-compute-terraform, hashicorp/policy-library-azure-storage-terraform).

Hi @sduff 

We decided to be intentional with how we worded the readme because "Sentinel Policies" can mean many things to different folks and we wanted to put emphasis on the fact that these policies were written for Terraform and not Vault, Nomad, or Consul. We also may include support for other policy as code frameworks in the future so calling out the framework seemed unnecessary.

**Comment by sduff** [comment]
Thanks for the explanation @hcrhall , but note that the heading of the repo refers to "Sentinel Policies for Terraform".
I'm happy to close out this PR and just put it down to me being pedantic :)

**Pull request closed without merging**
